// This file is generated by FlutterFire CLI.
// Do not manually edit this file unless you know what you are doing.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase projects.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmtxhF6QQGjV7mC_CWJfdSNIEaPQMsFo',
    appId: '1:673006629953:web:dummywebid123456',
    messagingSenderId: '673006629953',
    projectId: 'lucifax-cdm',
    authDomain: 'lucifax-cdm.firebaseapp.com',
    storageBucket: 'lucifax-cdm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmtxhF6QQGjV7mC_CWJfdSNIEaPQMsFo',
    appId: '1:673006629953:android:82f29841989d73ccc142c0',
    messagingSenderId: '673006629953',
    projectId: 'lucifax-cdm',
    storageBucket: 'lucifax-cdm.firebasestorage.app',
  );
}
